# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/berry:$COMMIT_SHA', '.'] # Tag with commit SHA

images: ['asia-south1-docker.pkg.dev/$PROJECT_ID/berry:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

# Add a service account for builds (best practice)
serviceAccount: 'cloud-build-service-ac@$PROJECT_ID.iam.gserviceaccount.com' # Replace!

# Add artifacts for storing build outputs (best practice)
artifacts:
  objects:
    location: 'gs://berry-images' # Replace!
    paths:
      - 'my-output-file.zip' # Example: Add paths to your build outputs
